[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "maxrl-statistics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.2",
    "einops>=0.8.2",
    "ipykernel>=7.2.0",
    "jaxtyping>=0.3.9",
    "jupyter>=1.1.1",
    "lightning-fabric>=2.6.1",
    "matplotlib>=3.10.8",
    "muon-optimizer",
    "plotly>=6.7.0",
    "polars>=1.39.3",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "solara>=1.57.3",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "tqdm>=4.67.3",
    "transformers>=5.5.3",
    "wandb>=0.25.1",
]


[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
muon-optimizer = { git = "https://github.com/KellerJordan/Muon" }

[tool.setuptools.packages.find]
include = ["src*"]

[dependency-groups]
dev = [
    "kaleido>=1.2.0",
    "pytest>=9.0.3",
    "ruff>=0.15.10",
]

[tool.ruff.format]
preview = true

[tool.ruff.lint]
# Jaxtyping fixes
per-file-ignores = {"**/*.py" = ["F821", "F722"]}
