project:
  output-dir: ../docs
  render:
    - index.qmd
  resources:
    - assets/**

format:
  html:
    theme: default
    toc: true
    toc-depth: 3

execute:
  echo: false
  warning: false
  message: false
