from math import isfinite
from typing import Self

import numpy as np

from src.data.bag_of_words import BagOfWordsDatasetConfig


class RowHeterogeneousBagOfWordsDatasetConfig(BagOfWordsDatasetConfig):
    """
    Bag-of-words with harmonic-beta row-noise heteroskedasticity.

    The base bag-of-words has homoskedastic noise.

    This variant injects **row-level heteroskedastic noise** via the harmonic-beta
    law on the local squared correlation q_i = rho_i². With m = corr²,
        α = 1 + row_hardness_eta
        β = row_hardness_eta · (1 - m) / m
        q_i ~ Beta(α, β)
        ã_i² = m / (1 - m) · (1 / q_i - 1)
    and the realized split is empirically renormalized to a_i² = ã_i² / mean_i(ã_i²)
    so that mean_i(a_i²) = 1. This preserves the **global** correlation
    Corr(signal, target) = corr exactly; per-row local correlation
    rho_i = corr / sqrt(corr² + (1 - corr²) · a_i²).

    row_hardness_eta controls the tail of a_i²: small eta → heavy tail (rare
    very hard rows), large eta → near-homogeneous. Require eta > 1 so the
    population variance of a_i² is finite. corr = 0 is disallowed (the
    harmonic-beta coordinate requires division by m); corr = 1 collapses to a
    point mass a_i = 1.
    """

    row_hardness_eta: float

    @classmethod
    def initialize(
        cls,
        *,
        row_hardness_eta: float,
        **base_cls_kwargs,
    ) -> Self:
        if not isfinite(row_hardness_eta) or row_hardness_eta <= 1:
            raise ValueError("row_hardness_eta must be finite and > 1")
        base_kwargs = cls._base_kwargs(**base_cls_kwargs)
        if base_kwargs["corr"] <= 0:
            raise ValueError("corr must be > 0 for harmonic-beta heteroskedasticity")
        return cls(**base_kwargs, row_hardness_eta=row_hardness_eta)

    @classmethod
    def raw_noise_schedule(
        cls,
        *,
        corr: float,
        row_hardness_eta: float,
        rng: np.random.Generator,
        n: int,
    ) -> np.ndarray:
        """
        Draw n samples of ã_i² (pre mean-normalization) from the harmonic-beta
        law. At corr = 1 the distribution collapses to a point mass at 1.

        Pre mean-normalization. Expose it so visualization and writeup scripts
        can evaluate the same schedule without rebuilding the sampling pipeline.
        """
        if corr == 1.0:
            return np.ones(n, dtype=float)
        m = corr**2
        alpha = 1.0 + row_hardness_eta
        beta = row_hardness_eta * (1.0 - m) / m
        q_raw = rng.beta(alpha, beta, size=n)
        return (m / (1.0 - m)) * (1.0 / q_raw - 1.0)

    def _compute_split(
        self, *, split: str, rng: np.random.Generator
    ) -> "BagOfWordsDatasetConfig.SplitArtifact":
        n = {"train": self.num_train_samples, "val": self.num_val_samples}[split]
        words = list(self.word_density)
        probs = np.array([self.word_density[w] for w in words], dtype=float)
        vals = np.array([self.word_values[w] for w in words], dtype=float)
        vocab = np.asarray(words, dtype=object)

        idx = rng.choice(len(words), size=(n, self.prompt_length), p=probs)
        raw = vals[idx].sum(axis=1)
        signal = (
            raw / ((self.prompt_length**0.5) * self.unnormalized_signal_std) * self.corr
        )

        # Harmonic-beta schedule, empirically renormalized so mean(a²) = 1.
        a_sq_raw = type(self).raw_noise_schedule(
            corr=self.corr,
            row_hardness_eta=self.row_hardness_eta,
            rng=rng,
            n=n,
        )
        a = np.sqrt(a_sq_raw / np.mean(a_sq_raw))

        noise_std_global = (1 - self.corr**2) ** 0.5
        targets = signal + noise_std_global * a * rng.standard_normal(n)
        prompts = [" ".join(vocab[row]) for row in idx]
        return self.SplitArtifact(prompts=prompts, signal=signal, targets=targets)


class SignalHeterogeneousBagOfWordsDatasetConfig(BagOfWordsDatasetConfig):
    """
    Bag-of-words with prompt-conditioned semantic heteroskedasticity.

    Each semantic word w is assigned a deterministic hardness quantile q(w),
    ranked by absolute signal magnitude so that high-|value| words are hardest.
    This induces a raw semantic-word noise-std multiplier
        ã(w) = 2 ** ((q(w) - 1/2) / snr_halflife_in_word_quantile)

    Auxiliary words contribute zero signal and zero variance budget:
        ã(w_aux) = 0.

    For a prompt x = (w_1, ..., w_L), define the raw prompt variance multiplier
        Ã(x)^2 = (1 / L) * Σ_j ã(w_j)^2

    and normalize it so
        E[A(x)^2] = 1
    under the prompt distribution.

    Targets are generated by
        signal(x) = corr * sum_j v(w_j) / (sqrt(L) * sigma)
        target(x) = signal(x) + sqrt(1 - corr^2) * A(x) * ε

    preserving the global Corr(signal, target) = corr exactly.

    snr_halflife_in_word_quantile is the quantile-distance over which the
    semantic-word noise std doubles, equivalently its local SNR halves.

    The induced prompt-conditioned correlation is
        rho(x) = corr / sqrt(corr^2 + (1 - corr^2) * A(x)^2).
    """

    snr_halflife_in_word_quantile: float

    @classmethod
    def initialize(
        cls,
        *,
        snr_halflife_in_word_quantile: float,
        **base_cls_kwargs,
    ) -> Self:
        if (
            not isfinite(snr_halflife_in_word_quantile)
            or snr_halflife_in_word_quantile <= 0
        ):
            raise ValueError(
                "snr_halflife_in_word_quantile must be finite and positive"
            )
        return cls(
            **cls._base_kwargs(**base_cls_kwargs),
            snr_halflife_in_word_quantile=snr_halflife_in_word_quantile,
        )

    @classmethod
    def word_multipliers(
        cls,
        *,
        word_assignments: tuple[str, ...],
        word_values: dict[str, int],
        snr_halflife_in_word_quantile: float,
    ) -> dict[str, float]:
        """
        Pre-normalization ã(w) for every word in `word_values`.

        Semantic words (those in `word_assignments`) are ranked by |value|;
        words sharing the same |value| share the same quantile (average rank
        within their tie group), preserving sign symmetry. Any word in
        `word_values` but not in `word_assignments` is treated as auxiliary
        and gets ã = 0.

        Exposed so visualization and writeup scripts can recover the per-word
        difficulty directly from a config without rerunning the sampling
        pipeline.
        """
        semantic = list(word_assignments)
        num_semantic = len(semantic)
        groups_by_abs: dict[int, list[int]] = {}
        for i, word in enumerate(semantic):
            groups_by_abs.setdefault(abs(int(word_values[word])), []).append(i)
        result: dict[str, float] = {word: 0.0 for word in word_values}
        cumulative = 0
        for abs_val in sorted(groups_by_abs):
            group = groups_by_abs[abs_val]
            avg_rank = cumulative + (len(group) - 1) / 2
            q = (avg_rank + 0.5) / num_semantic
            multiplier = 2.0 ** ((q - 0.5) / snr_halflife_in_word_quantile)
            for i in group:
                result[semantic[i]] = multiplier
            cumulative += len(group)
        return result

    @classmethod
    def sample_prompt_variance_multiplier(
        cls,
        *,
        word_assignments: tuple[str, ...],
        word_values: dict[str, int],
        word_density: dict[str, float],
        snr_halflife_in_word_quantile: float,
        prompt_length: int,
        n: int,
        rng: np.random.Generator,
    ) -> tuple[np.ndarray, dict[str, float]]:
        """
        Sample n prompts and return the normalized prompt-level variance
        multiplier A²(x) alongside the normalized per-word hardness
        a(w) = ã(w) / sqrt(E_w[ã²]). Both normalizations use the same
        expected raw variance, so E[A²] = 1 and E_w[a(w)²] = 1 under the
        word distribution.

        Exposed so visualization and writeup scripts can evaluate the same
        prompt-level schedule without re-implementing its sampling and
        normalization.
        """
        words = list(word_density)
        probs = np.array([word_density[w] for w in words], dtype=float)
        tilde_a_per_word = cls.word_multipliers(
            word_assignments=word_assignments,
            word_values=word_values,
            snr_halflife_in_word_quantile=snr_halflife_in_word_quantile,
        )
        tilde_a = np.array([tilde_a_per_word[w] for w in words], dtype=float)
        expected_tilde_sq = float(np.sum(probs * tilde_a**2))
        idx = rng.choice(len(words), size=(n, prompt_length), p=probs)
        A_sq = (tilde_a[idx] ** 2).mean(axis=1) / expected_tilde_sq
        scale = float(np.sqrt(expected_tilde_sq))
        normalized_word_hardness = {
            word: tilde_a_per_word[word] / scale for word in tilde_a_per_word
        }
        return A_sq, normalized_word_hardness

    def _compute_split(
        self, *, split: str, rng: np.random.Generator
    ) -> "BagOfWordsDatasetConfig.SplitArtifact":
        n = {"train": self.num_train_samples, "val": self.num_val_samples}[split]
        words = list(self.word_density)
        probs = np.array([self.word_density[w] for w in words], dtype=float)
        vals = np.array([self.word_values[w] for w in words], dtype=float)
        vocab = np.asarray(words, dtype=object)

        idx = rng.choice(len(words), size=(n, self.prompt_length), p=probs)
        raw = vals[idx].sum(axis=1)
        signal = (
            raw / ((self.prompt_length**0.5) * self.unnormalized_signal_std) * self.corr
        )

        # Prompt-level variance multiplier, RMS-normalized so E[A²] = 1.
        tilde_a_per_word = type(self).word_multipliers(
            word_assignments=self.word_assignments,
            word_values=self.word_values,
            snr_halflife_in_word_quantile=self.snr_halflife_in_word_quantile,
        )
        tilde_a = np.array([tilde_a_per_word[w] for w in words], dtype=float)
        expected_tilde_sq = float(np.sum(probs * tilde_a**2))
        A = np.sqrt((tilde_a[idx] ** 2).mean(axis=1) / expected_tilde_sq)

        noise_std_global = (1 - self.corr**2) ** 0.5
        targets = signal + noise_std_global * A * rng.standard_normal(n)
        prompts = [" ".join(vocab[row]) for row in idx]
        return self.SplitArtifact(prompts=prompts, signal=signal, targets=targets)
