from math import isfinite
from typing import Self

import numpy as np

from src.data.bag_of_words import BagOfWordsDatasetConfig


class RowHeterogeneousBagOfWordsDatasetConfig(BagOfWordsDatasetConfig):
    """
    Bag-of-words with median-pegged exponential row-noise heteroskedasticity.

    The base bag-of-words has homoskedastic noise.

    This variant injects **row-level heteroskedastic noise** along a hardness
    quantile. Each row i is assigned a quantile u_i on a random stratified grid,
    giving a median-pegged exponential noise-std multiplier
        ã(u) = 2 ** ((u - 1/2) / snr_halflife_in_quantile)
    which is then RMS-normalized so E[a²] = 1. This preserves the **global**
    correlation Corr(signal, target) = corr exactly; per-row local correlation
    rho_i = corr / sqrt(corr² + (1 - corr²) · a_i²).

    snr_halflife_in_quantile is the quantile-distance over which SNR halves / doubles.
    """

    snr_halflife_in_quantile: float

    @classmethod
    def initialize(
        cls,
        *,
        snr_halflife_in_quantile: float,
        **base_cls_kwargs,
    ) -> Self:
        if not isfinite(snr_halflife_in_quantile) or snr_halflife_in_quantile <= 0:
            raise ValueError("snr_halflife_in_quantile must be finite and positive")
        return cls(
            **cls._base_kwargs(**base_cls_kwargs),
            snr_halflife_in_quantile=snr_halflife_in_quantile,
        )

    @classmethod
    def raw_noise_schedule(
        cls, *, quantiles: np.ndarray, snr_halflife_in_quantile: float
    ) -> np.ndarray:
        """
        Raw median-pegged exponential multiplier ã(u) = 2^((u - 1/2) / halflife).

        Pre RMS-normalization. Expose it so visualization and writeup scripts
        can evaluate the same schedule on any quantile grid without rebuilding
        the sampling pipeline.
        """
        return 2.0 ** ((quantiles - 0.5) / snr_halflife_in_quantile)

    def _compute_split(
        self, *, split: str, rng: np.random.Generator
    ) -> "BagOfWordsDatasetConfig.SplitArtifact":
        n = {"train": self.num_train_samples, "val": self.num_val_samples}[split]
        words = list(self.word_density)
        probs = np.array([self.word_density[w] for w in words], dtype=float)
        vals = np.array([self.word_values[w] for w in words], dtype=float)
        vocab = np.asarray(words, dtype=object)

        idx = rng.choice(len(words), size=(n, self.prompt_length), p=probs)
        raw = vals[idx].sum(axis=1)
        signal = (
            raw / ((self.prompt_length**0.5) * self.unnormalized_signal_std) * self.corr
        )

        # Median-pegged exponential schedule on stratified hardness quantiles.
        u = (rng.permutation(n) + 0.5) / n
        tilde_a = type(self).raw_noise_schedule(
            quantiles=u, snr_halflife_in_quantile=self.snr_halflife_in_quantile
        )
        a = tilde_a / np.sqrt(np.mean(tilde_a**2))

        noise_std_global = (1 - self.corr**2) ** 0.5
        targets = signal + noise_std_global * a * rng.standard_normal(n)
        prompts = [" ".join(vocab[row]) for row in idx]
        return self.SplitArtifact(prompts=prompts, signal=signal, targets=targets)


class SignalHeterogeneousBagOfWordsDatasetConfig(BagOfWordsDatasetConfig):
    """
    Bag-of-words with prompt-conditioned semantic heteroskedasticity.

    Each semantic word w is assigned a deterministic hardness quantile q(w),
    ranked by absolute signal magnitude so that high-|value| words are hardest.
    This induces a raw semantic-word noise-std multiplier
        ã(w) = 2 ** ((q(w) - 1/2) / snr_halflife_in_word_quantile)

    Auxiliary words contribute zero signal and zero variance budget:
        ã(w_aux) = 0.

    For a prompt x = (w_1, ..., w_L), define the raw prompt variance multiplier
        Ã(x)^2 = (1 / L) * Σ_j ã(w_j)^2

    and normalize it so
        E[A(x)^2] = 1
    under the prompt distribution.

    Targets are generated by
        signal(x) = corr * sum_j v(w_j) / (sqrt(L) * sigma)
        target(x) = signal(x) + sqrt(1 - corr^2) * A(x) * ε

    preserving the global Corr(signal, target) = corr exactly.

    snr_halflife_in_word_quantile is the quantile-distance over which the
    semantic-word noise std doubles, equivalently its local SNR halves.

    The induced prompt-conditioned correlation is
        rho(x) = corr / sqrt(corr^2 + (1 - corr^2) * A(x)^2).
    """

    snr_halflife_in_word_quantile: float

    @classmethod
    def initialize(
        cls,
        *,
        snr_halflife_in_word_quantile: float,
        **base_cls_kwargs,
    ) -> Self:
        if (
            not isfinite(snr_halflife_in_word_quantile)
            or snr_halflife_in_word_quantile <= 0
        ):
            raise ValueError(
                "snr_halflife_in_word_quantile must be finite and positive"
            )
        return cls(
            **cls._base_kwargs(**base_cls_kwargs),
            snr_halflife_in_word_quantile=snr_halflife_in_word_quantile,
        )

    @classmethod
    def word_multipliers(
        cls,
        *,
        word_assignments: tuple[str, ...],
        word_values: dict[str, int],
        snr_halflife_in_word_quantile: float,
    ) -> dict[str, float]:
        """
        Pre-normalization ã(w) for every word in `word_values`.

        Semantic words (those in `word_assignments`) are ranked by |value|;
        words sharing the same |value| share the same quantile (average rank
        within their tie group), preserving sign symmetry. Any word in
        `word_values` but not in `word_assignments` is treated as auxiliary
        and gets ã = 0.

        Exposed so visualization and writeup scripts can recover the per-word
        difficulty directly from a config without rerunning the sampling
        pipeline.
        """
        semantic = list(word_assignments)
        num_semantic = len(semantic)
        groups_by_abs: dict[int, list[int]] = {}
        for i, word in enumerate(semantic):
            groups_by_abs.setdefault(abs(int(word_values[word])), []).append(i)
        result: dict[str, float] = {word: 0.0 for word in word_values}
        cumulative = 0
        for abs_val in sorted(groups_by_abs):
            group = groups_by_abs[abs_val]
            avg_rank = cumulative + (len(group) - 1) / 2
            q = (avg_rank + 0.5) / num_semantic
            multiplier = 2.0 ** ((q - 0.5) / snr_halflife_in_word_quantile)
            for i in group:
                result[semantic[i]] = multiplier
            cumulative += len(group)
        return result

    def _compute_split(
        self, *, split: str, rng: np.random.Generator
    ) -> "BagOfWordsDatasetConfig.SplitArtifact":
        n = {"train": self.num_train_samples, "val": self.num_val_samples}[split]
        words = list(self.word_density)
        probs = np.array([self.word_density[w] for w in words], dtype=float)
        vals = np.array([self.word_values[w] for w in words], dtype=float)
        vocab = np.asarray(words, dtype=object)

        tilde_a_per_word = type(self).word_multipliers(
            word_assignments=self.word_assignments,
            word_values=self.word_values,
            snr_halflife_in_word_quantile=self.snr_halflife_in_word_quantile,
        )
        tilde_a = np.array([tilde_a_per_word[w] for w in words], dtype=float)

        idx = rng.choice(len(words), size=(n, self.prompt_length), p=probs)
        raw = vals[idx].sum(axis=1)
        signal = (
            raw / ((self.prompt_length**0.5) * self.unnormalized_signal_std) * self.corr
        )

        # Prompt-level variance multiplier, RMS-normalized so E[A²] = 1.
        expected_tilde_sq = float(np.sum(probs * tilde_a**2))
        tilde_A_sq = (tilde_a[idx] ** 2).mean(axis=1)
        A = np.sqrt(tilde_A_sq / expected_tilde_sq)

        noise_std_global = (1 - self.corr**2) ** 0.5
        targets = signal + noise_std_global * A * rng.standard_normal(n)
        prompts = [" ".join(vocab[row]) for row in idx]
        return self.SplitArtifact(prompts=prompts, signal=signal, targets=targets)
